server:
  port: 8002

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1 #指定服务使用的ip地址
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port} #指定实例id

spring:
  application:
    name: microservice-shop-member
  mail:
    host: smtp.163.com
    username: 15893812649@163.com
    password: wolf123
    enable:  true
    smtp:
      auth: true
    starttls:
      enable: true
      required: true



